/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucas.sysvendas.view.cadastro;

import com.lucas.sysvendas.control.ClienteControl;
import com.lucas.sysvendas.model.domain.Cliente;
import com.lucas.sysvendas.model.domain.ClienteEndereco;
import com.lucas.sysvendas.util.ValidacaoCpfCnpj;
import com.lucas.sysvendas.util.ValidacaoEmail;
import com.lucas.sysvendas.util.exceptions.ErroException;
import com.towel.swing.table.ObjectTableModel;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author lucas
 */
public class TelaCliente extends javax.swing.JInternalFrame {
    
    private final ObjectTableModel<Cliente> otmCliente = new ObjectTableModel<>(Cliente.class, "codigo,nomeFantasia,cpfCnpj,tipoPessoa,telefone,celular,email");
    private final ObjectTableModel<ClienteEndereco> otmClienteEndereco = new ObjectTableModel<>(ClienteEndereco.class, "endereco,numero,bairro,complemento,cidade,estado,cep");
    
    private final ClienteControl clienteControl = new ClienteControl();
    
    private Cliente cliente;
    private ClienteEndereco clienteEndereco;
    
    private String statusBotoes;

    /**
     * Creates new form TelaFuncionario
     */
    public TelaCliente() {
        
        initComponents();
        
        habilitarFormulario(false);
        
        carregarGrade();
        
        if (tpCliente.getSelectedRowCount() > 0) {
            
            int linhaSelecionada = tpCliente.getRowSorter().convertRowIndexToModel(tpCliente.getSelectedRow());
            Cliente clienteSelecionado = otmCliente.getValue(linhaSelecionada);

            try {
                otmClienteEndereco.setData(clienteControl.recuperarEndereco(clienteSelecionado));
            } catch (ErroException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar o endereço do cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }
    
    
    private void carregarGrade() {
        
        try {      
            otmCliente.setData(clienteControl.listarTodos());
        } catch (ErroException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClienteTipo = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        pBarraFerramentas = new javax.swing.JPanel();
        bNovo = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        tpConteudoCliente = new javax.swing.JTabbedPane();
        paDadosCliente = new javax.swing.JPanel();
        lblNomeFantasia = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblCpfCnpj = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpCliente = new javax.swing.JTable();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblTipoPessoa = new javax.swing.JLabel();
        rbFisica = new javax.swing.JRadioButton();
        rbJuridica = new javax.swing.JRadioButton();
        txtTelefone = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        ftfCpfCnpj = new javax.swing.JFormattedTextField();
        paDadosClienteEndereco = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpClienteEndereco = new javax.swing.JTable();
        txtBairro = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        txtUf = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        bAdicionarEndereco = new javax.swing.JButton();
        bRemoverEndereco = new javax.swing.JButton();
        bEditarEndereco = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes");

        bNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        bNovo.setMnemonic(KeyEvent.VK_N);
        bNovo.setText("Novo");
        bNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });

        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        bSalvar.setMnemonic(KeyEvent.VK_S);
        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        bRemover.setMnemonic(KeyEvent.VK_R);
        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        bCancelar.setMnemonic(KeyEvent.VK_C);
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBarraFerramentasLayout = new javax.swing.GroupLayout(pBarraFerramentas);
        pBarraFerramentas.setLayout(pBarraFerramentasLayout);
        pBarraFerramentasLayout.setHorizontalGroup(
            pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(bNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancelar)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pBarraFerramentasLayout.setVerticalGroup(
            pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addComponent(bNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblNomeFantasia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNomeFantasia.setText("Nome Fantasia:");

        txtNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeFantasiaKeyPressed(evt);
            }
        });

        lblRazaoSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRazaoSocial.setText("Razão Social:");

        txtRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazaoSocialKeyPressed(evt);
            }
        });

        lblCpfCnpj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpfCnpj.setText("CPF/CNPJ:");

        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText("Telefone:");

        tpCliente.setModel(otmCliente);
        tpCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpCliente);

        lblDocumento.setText("I.E./RG:");

        lblTipoPessoa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoPessoa.setText("Tipo Pessoa:");

        bgClienteTipo.add(rbFisica);
        rbFisica.setText("Física");
        rbFisica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbFisicaItemStateChanged(evt);
            }
        });

        bgClienteTipo.add(rbJuridica);
        rbJuridica.setText("Jurídica");
        rbJuridica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbJuridicaItemStateChanged(evt);
            }
        });

        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("Celular:");

        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("Email:");

        javax.swing.GroupLayout paDadosClienteLayout = new javax.swing.GroupLayout(paDadosCliente);
        paDadosCliente.setLayout(paDadosClienteLayout);
        paDadosClienteLayout.setHorizontalGroup(
            paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(paDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTipoPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCpfCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeFantasia)
                    .addComponent(txtRazaoSocial)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paDadosClienteLayout.createSequentialGroup()
                        .addComponent(ftfCpfCnpj)
                        .addGap(18, 18, 18)
                        .addComponent(lblDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paDadosClienteLayout.createSequentialGroup()
                        .addComponent(rbFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbJuridica))
                    .addGroup(paDadosClienteLayout.createSequentialGroup()
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addComponent(txtEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paDadosClienteLayout.setVerticalGroup(
            paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPessoa)
                    .addComponent(rbFisica)
                    .addComponent(rbJuridica))
                .addGap(5, 5, 5)
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFantasia)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCnpj)
                    .addComponent(lblDocumento)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tpConteudoCliente.addTab("Dados", paDadosCliente);

        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEndereco.setText("Endereço:");

        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumero.setText("Número:");

        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBairro.setText("Bairro:");

        lblComplemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblComplemento.setText("Complemento:");

        tpClienteEndereco.setModel(otmClienteEndereco);
        tpClienteEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpClienteEnderecoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tpClienteEndereco);

        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCidade.setText("Cidade:");

        lblUf.setText("UF:");

        lblCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCep.setText("CEP:");

        bAdicionarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        bAdicionarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarEnderecoActionPerformed(evt);
            }
        });

        bRemoverEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        bRemoverEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverEnderecoActionPerformed(evt);
            }
        });

        bEditarEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        bEditarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paDadosClienteEnderecoLayout = new javax.swing.GroupLayout(paDadosClienteEndereco);
        paDadosClienteEndereco.setLayout(paDadosClienteEnderecoLayout);
        paDadosClienteEnderecoLayout.setHorizontalGroup(
            paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(paDadosClienteEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paDadosClienteEnderecoLayout.createSequentialGroup()
                        .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paDadosClienteEnderecoLayout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paDadosClienteEnderecoLayout.createSequentialGroup()
                        .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplemento)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paDadosClienteEnderecoLayout.createSequentialGroup()
                                .addComponent(txtCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paDadosClienteEnderecoLayout.createSequentialGroup()
                                .addComponent(bAdicionarEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEditarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bRemoverEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paDadosClienteEnderecoLayout.setVerticalGroup(
            paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paDadosClienteEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUf)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paDadosClienteEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bRemoverEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEditarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAdicionarEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tpConteudoCliente.addTab("Endereço", paDadosClienteEndereco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBarraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tpConteudoCliente)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pBarraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(tpConteudoCliente)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        cliente = clienteControl.novoCliente();
        habilitarFormulario(true);
        bRemover.setEnabled(false);
        txtNomeFantasia.requestFocus();
    }//GEN-LAST:event_bNovoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        habilitarFormulario(false);
        
        otmClienteEndereco.clear();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tpClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpClienteMouseClicked
        if (evt.getClickCount() >= 2) {
            cliente = otmCliente.getValue(tpCliente.getSelectedRow());
            
            if (cliente.getTipoPessoa().equals("Fisica")) {
                rbFisica.setSelected(true);
            } else if(cliente.getTipoPessoa().equals("Juridica")){
                rbJuridica.setSelected(true);
            }
            txtNomeFantasia.setText(cliente.getNomeFantasia());
            txtRazaoSocial.setText(cliente.getRazaoSocial());
            ftfCpfCnpj.setValue(cliente.getCpfCnpj());
            txtDocumento.setText(cliente.getDocumento());
            txtTelefone.setText(cliente.getTelefone());
            txtCelular.setText(cliente.getCelular());
            txtEmail.setText(cliente.getEmail());
            
            try {
                otmClienteEndereco.setData(clienteControl.recuperarEndereco(cliente));
            } catch (ErroException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar o endereço do cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

            habilitarFormulario(true);

        }
    }//GEN-LAST:event_tpClienteMouseClicked

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        if (validarFormulario()) {
            
            if(rbFisica.isSelected()) {
               cliente.setTipoPessoa("Fisica"); 
            } else if (rbJuridica.isSelected()){
               cliente.setTipoPessoa("Juridica");
            }
            cliente.setNomeFantasia(txtNomeFantasia.getText().trim());
            cliente.setRazaoSocial(txtRazaoSocial.getText());
            cliente.setDataCadastro(new Date());
            cliente.setCpfCnpj((String) ftfCpfCnpj.getValue());
            cliente.setDocumento(txtDocumento.getText());
            cliente.setTelefone(txtTelefone.getText());
            cliente.setCelular(txtCelular.getText());
            cliente.setEmail(txtEmail.getText());


            if (cliente.getCodigo() == 0) {
                try {
                    clienteControl.inserirCliente(cliente);
                } catch (ErroException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                try {
                    clienteControl.alterarCliente(cliente);
                } catch (ErroException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } 

            habilitarFormulario(false);
            carregarGrade();
            
            otmClienteEndereco.clear();
        }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void txtNomeFantasiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFantasiaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          txtRazaoSocial.requestFocus();
        }
    }//GEN-LAST:event_txtNomeFantasiaKeyPressed

    private void txtRazaoSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazaoSocialKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          ftfCpfCnpj.requestFocus();
        }
    }//GEN-LAST:event_txtRazaoSocialKeyPressed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o cliente " + cliente + "?");
        if (opcao == 0) {
            try {
                clienteControl.excluirCliente(cliente);
            } catch (ErroException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            habilitarFormulario(false);
            carregarGrade();
        }
    }//GEN-LAST:event_bRemoverActionPerformed

    private void tpClienteEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpClienteEnderecoMouseClicked
        if (evt.getClickCount() >= 2) {
            
            clienteEndereco = otmClienteEndereco.getValue(tpClienteEndereco.getSelectedRow());
            
            txtEndereco.setText(clienteEndereco.getEndereco());
            txtNumero.setText(clienteEndereco.getNumero());
            txtBairro.setText(clienteEndereco.getBairro());
            txtComplemento.setText(clienteEndereco.getComplemento());
            txtCidade.setText(clienteEndereco.getCidade());
            txtUf.setText(clienteEndereco.getEstado());
            txtCep.setText(clienteEndereco.getCep());

            habilitarFormulario(true);

        }
    }//GEN-LAST:event_tpClienteEnderecoMouseClicked

    private void rbFisicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbFisicaItemStateChanged
        try {
            ftfCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("###.###.###-##")));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o tipo do cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbFisicaItemStateChanged

    private void rbJuridicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbJuridicaItemStateChanged
        try {
            ftfCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##.###.###/####-##")));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao selecionar o tipo do cliente.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbJuridicaItemStateChanged

    private void bAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarEnderecoActionPerformed
        
        statusBotoes = "Adicionando";
        
        setarClienteEndereco();
        
        otmClienteEndereco.setData(cliente.getEndereco());
        
        limpaFormularioClienteEndereco();
        
    }//GEN-LAST:event_bAdicionarEnderecoActionPerformed

    private void bRemoverEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverEnderecoActionPerformed
        if (tpClienteEndereco.getSelectedRowCount() > 0) {
            
            int linhaSelecionada = tpClienteEndereco.getSelectedRow();
            ClienteEndereco enderecoRemover = otmClienteEndereco.getValue(linhaSelecionada);

            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o endereço " + enderecoRemover + "?", "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
                cliente.getEndereco().remove(enderecoRemover);
                otmClienteEndereco.setData(cliente.getEndereco());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para remover.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bRemoverEnderecoActionPerformed

    private void bEditarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarEnderecoActionPerformed
        statusBotoes = "Alterando";
        
        setarClienteEndereco();
        
        otmClienteEndereco.setData(cliente.getEndereco());
        
        limpaFormularioClienteEndereco();
    }//GEN-LAST:event_bEditarEnderecoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionarEndereco;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bEditarEndereco;
    private javax.swing.JButton bNovo;
    private javax.swing.JButton bRemover;
    private javax.swing.JButton bRemoverEndereco;
    private javax.swing.JButton bSalvar;
    private javax.swing.ButtonGroup bgClienteTipo;
    private javax.swing.JFormattedTextField ftfCpfCnpj;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoPessoa;
    private javax.swing.JLabel lblUf;
    private javax.swing.JPanel pBarraFerramentas;
    private javax.swing.JPanel paDadosCliente;
    private javax.swing.JPanel paDadosClienteEndereco;
    private javax.swing.JRadioButton rbFisica;
    private javax.swing.JRadioButton rbJuridica;
    private javax.swing.JTable tpCliente;
    private javax.swing.JTable tpClienteEndereco;
    private javax.swing.JTabbedPane tpConteudoCliente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables

private void habilitarFormulario(boolean b) {
    
        bNovo.setEnabled(!b);
        bSalvar.setEnabled(b);
        bRemover.setEnabled(b);
        bCancelar.setEnabled(b);
        rbFisica.setEnabled(b);
        rbJuridica.setEnabled(b);
        txtNomeFantasia.setEnabled(b);
        txtRazaoSocial.setEnabled(b);
        ftfCpfCnpj.setEnabled(b);
        txtDocumento.setEnabled(b);
        txtTelefone.setEnabled(b);
        txtCelular.setEnabled(b);
        txtEmail.setEnabled(b);
        txtEndereco.setEnabled(b);
        txtNumero.setEnabled(b);
        txtBairro.setEnabled(b);
        txtComplemento.setEnabled(b);
        txtCidade.setEnabled(b);
        txtUf.setEnabled(b);
        txtCep.setEnabled(b);
        tpCliente.setEnabled(!b);

        if (!b) {
            
            limpaFormulario();
            limpaFormularioClienteEndereco();
        }
    }

    private void limpaFormulario() {
        
        cliente = null;
        txtNomeFantasia.setText("");
        txtRazaoSocial.setText("");
        ftfCpfCnpj.setValue("");
        txtDocumento.setText("");
        txtTelefone.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        
    }
    
    private void limpaFormularioClienteEndereco() {

        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtComplemento.setText("");
        txtCidade.setText("");
        txtUf.setText("");
        txtCep.setText("");
    }
    
    private void setarClienteEndereco() {
        
        if (statusBotoes.equals("Adicionando")) {
            clienteEndereco = clienteControl.novoClienteEndereco();
        }
        
        clienteEndereco.setEndereco(txtEndereco.getText());
        clienteEndereco.setNumero(txtNumero.getText());
        clienteEndereco.setBairro(txtBairro.getText());
        clienteEndereco.setComplemento(txtComplemento.getText());
        clienteEndereco.setCidade(txtCidade.getText());
        clienteEndereco.setEstado(txtUf.getText());
        clienteEndereco.setCep(txtCep.getText());
        
        cliente.getEndereco().add(clienteEndereco);
    }
    
    
    private boolean validarFormulario() {
        
        ValidacaoCpfCnpj vCnj = new ValidacaoCpfCnpj();
        ValidacaoEmail vEmail = new ValidacaoEmail();
        
        if (txtNomeFantasia.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(this, "Nome inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            txtNomeFantasia.requestFocus();
            return false;
        }
        
        if (vCnj.isValid(ftfCpfCnpj.getText().trim())==false) {
            JOptionPane.showMessageDialog(this, "CPF ou CNPJ inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfCpfCnpj.requestFocus();
            return false;
        }
        
        if (vEmail.validaEmail(txtEmail.getText().trim())==false) {
            JOptionPane.showMessageDialog(this, "Email inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            txtEmail.requestFocus();
            return false;
        }
        
        return true;
    }

}
