/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucas.sysvendas.view.cadastro;

import com.lucas.sysvendas.control.ProdutoControl;
import com.lucas.sysvendas.model.domain.Produto;
import com.lucas.sysvendas.report.Relatorio;
import com.lucas.sysvendas.util.exceptions.ErroException;
import com.towel.swing.table.ObjectTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaProduto extends javax.swing.JInternalFrame {
    
    private final ObjectTableModel<Produto> otmProduto = new ObjectTableModel<>(Produto.class, "descricao,quantidadeEstoque");
    
    private final ProdutoControl produtoControl = new ProdutoControl();
    
    private Produto produto;
    
    private Relatorio relatorio;

    /**
     * Creates new form TelaDepartamento
     */
    public TelaProduto() {
        initComponents();
        habilitarFormulario(false);
        carregarGrade();
    }
    
    private void carregarGrade() {
        
        try {      
            otmProduto.setData(produtoControl.listarTodos());
        } catch (ErroException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBarraFerramentas = new javax.swing.JPanel();
        bNovoProduto = new javax.swing.JButton();
        bSalvarProduto = new javax.swing.JButton();
        bRemoverProduto = new javax.swing.JButton();
        bCancelarProduto = new javax.swing.JButton();
        bImprimir = new javax.swing.JButton();
        pConteudo = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpProduto = new javax.swing.JTable();
        lblPrecoCompra = new javax.swing.JLabel();
        ftfPrecoCompra = new javax.swing.JFormattedTextField();
        lblPrecoVenda = new javax.swing.JLabel();
        ftfPrecoVenda = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Produto");

        bNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        bNovoProduto.setText("Novo");
        bNovoProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoProdutoActionPerformed(evt);
            }
        });

        bSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        bSalvarProduto.setText("Salvar");
        bSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarProdutoActionPerformed(evt);
            }
        });

        bRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        bRemoverProduto.setText("Remover");
        bRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverProdutoActionPerformed(evt);
            }
        });

        bCancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        bCancelarProduto.setText("Cancelar");
        bCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarProdutoActionPerformed(evt);
            }
        });

        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impressora.png"))); // NOI18N
        bImprimir.setText("Imprimir");
        bImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBarraFerramentasLayout = new javax.swing.GroupLayout(pBarraFerramentas);
        pBarraFerramentas.setLayout(pBarraFerramentasLayout);
        pBarraFerramentasLayout.setHorizontalGroup(
            pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bNovoProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemoverProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancelarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBarraFerramentasLayout.setVerticalGroup(
            pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNovoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSalvarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bRemoverProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))))
                .addContainerGap())
        );

        lblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescricao.setText("Descrição:");

        tpProduto.setModel(otmProduto);
        tpProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpProduto);

        lblPrecoCompra.setText("Preço Compra:");

        lblPrecoVenda.setText("Preço Venda:");

        javax.swing.GroupLayout pConteudoLayout = new javax.swing.GroupLayout(pConteudo);
        pConteudo.setLayout(pConteudoLayout);
        pConteudoLayout.setHorizontalGroup(
            pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConteudoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pConteudoLayout.createSequentialGroup()
                        .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecoCompra)
                            .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftfPrecoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(ftfPrecoCompra, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pConteudoLayout.setVerticalGroup(
            pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConteudoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecoCompra)
                    .addComponent(ftfPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecoVenda)
                    .addComponent(ftfPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBarraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pBarraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoProdutoActionPerformed
        produto = new Produto();
        produto.setCodigo(0l);
        habilitarFormulario(true);
        txtDescricao.requestFocus();
    }//GEN-LAST:event_bNovoProdutoActionPerformed

    private void bSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarProdutoActionPerformed
        if (validarFormulario()) {
            produto.setDescricao(txtDescricao.getText());
            produto.setPrecoCompra((Double) ftfPrecoCompra.getValue());
            produto.setPrecoVenda((Double) ftfPrecoVenda.getValue());
            produto.setQuantidadeEstoque(0l);

            if (produto.getCodigo() == 0l) {
                try {
                    produtoControl.inserirProduto(produto);
                } catch (ErroException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar o usuário.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                try {
                    produtoControl.alterarProduto(produto);
                } catch (ErroException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar o usuário.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            habilitarFormulario(false);
            carregarGrade();
        }
    }//GEN-LAST:event_bSalvarProdutoActionPerformed

    private void bRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverProdutoActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o produto " + produto + "?");
        if (opcao == 0) {
            try {
                produtoControl.excluirProduto(produto);
            } catch (ErroException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o produto.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            habilitarFormulario(false);
            carregarGrade();
        }
    }//GEN-LAST:event_bRemoverProdutoActionPerformed

    private void bCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarProdutoActionPerformed
        habilitarFormulario(false);
    }//GEN-LAST:event_bCancelarProdutoActionPerformed

    private void tpProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpProdutoMouseClicked
        if (evt.getClickCount() >= 2) {
            produto = otmProduto.getValue(tpProduto.getSelectedRow());

            txtDescricao.setText(produto.getDescricao());
            ftfPrecoCompra.setValue(produto.getPrecoCompra());
            ftfPrecoVenda.setValue(produto.getPrecoVenda());

            habilitarFormulario(true);

        }
    }//GEN-LAST:event_tpProdutoMouseClicked

    private void bImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirActionPerformed
        gerarRelatorioProdutos();
    }//GEN-LAST:event_bImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarProduto;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton bNovoProduto;
    private javax.swing.JButton bRemoverProduto;
    private javax.swing.JButton bSalvarProduto;
    private javax.swing.JFormattedTextField ftfPrecoCompra;
    private javax.swing.JFormattedTextField ftfPrecoVenda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JPanel pBarraFerramentas;
    private javax.swing.JPanel pConteudo;
    private javax.swing.JTable tpProduto;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
    
    
    private void habilitarFormulario(boolean b) {
        bNovoProduto.setEnabled(!b);
        bSalvarProduto.setEnabled(b);
        bRemoverProduto.setEnabled(b);
        bCancelarProduto.setEnabled(b);
        txtDescricao.setEnabled(b);
        ftfPrecoCompra.setEnabled(b);
        ftfPrecoVenda.setEnabled(b);
        tpProduto.setEnabled(!b);

        if (!b) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {
        produto = null;
        txtDescricao.setText("");
        ftfPrecoCompra.setValue(new Double(0));
        ftfPrecoVenda.setValue(new Double(0));
    }
    
    private boolean validarFormulario() {
        if (txtDescricao.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Nome inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            txtDescricao.requestFocus();
            return false;
        }
        if (((Double) ftfPrecoCompra.getValue()) < 0) {
            JOptionPane.showMessageDialog(this, "Preço de compra inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfPrecoCompra.requestFocus();
            return false;
        }
        if (((Double) ftfPrecoVenda.getValue()) < 0) {
            JOptionPane.showMessageDialog(this, "Preço de venda inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfPrecoVenda.requestFocus();
            return false;
        }
        if (((Double) ftfPrecoVenda.getValue()) < ((Double) ftfPrecoCompra.getValue())) {
            JOptionPane.showMessageDialog(this, "Preço de venda menor que preço de compra.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfPrecoVenda.requestFocus();
            return false;
        }
        return true;
    }
    
    private void gerarRelatorioProdutos() {
        try {
            relatorio = new Relatorio();
            List<Produto> lProduto = produtoControl.listarTodos();
            String pathRelatorio = "src/main/resources/reports/Produtos.jasper";
            relatorio.gerarRelatorio(lProduto, null, pathRelatorio);
        } catch (ErroException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao imprimir o relatório.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }


}



