/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucas.sysvendas.view.cadastro;

import com.lucas.sysvendas.control.CompraControl;
import com.lucas.sysvendas.model.domain.Compra;
import com.lucas.sysvendas.model.domain.CompraItem;
import com.lucas.sysvendas.model.domain.Fornecedor;
import com.lucas.sysvendas.model.domain.Produto;
import com.lucas.sysvendas.model.enums.SituacaoEnum;
import com.lucas.sysvendas.view.consultas.TelaBuscaFornecedor;
import com.lucas.sysvendas.view.consultas.TelaBuscaProduto;
import com.towel.swing.table.ObjectTableModel;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class TelaCompra extends javax.swing.JInternalFrame {
    
    private final ObjectTableModel<Compra> otmCompra = new ObjectTableModel<>(Compra.class, "fornecedor,dataCompra,valorTotal,situacao");
    private final ObjectTableModel<CompraItem> otmCompraItem = new ObjectTableModel<>(CompraItem.class, "produto,quantidade,valorUnitario");
    
    private final CompraControl compraControl = new CompraControl();
    
    private Compra compra;
    private CompraItem compraItem;
    
    private String statusBotoes;

    /**
     * Creates new form TelaFuncionario
     */
    public TelaCompra() {
        
        initComponents();
        
        habilitarFormulario(false);
        
        carregarGrade();
        
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        ftfFornecedor.setValue(fornecedor);
    }
    
    public void setProduto(Produto produto) {
        ftfProduto.setValue(produto);
    }
    
    
    private void carregarGrade() {
        
        try {      
            otmCompra.setData(compraControl.listarTodos());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClienteTipo = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pBarraFerramentas = new javax.swing.JPanel();
        bNovo = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bFinalizar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bRemover = new javax.swing.JButton();
        tpConteudoCompra = new javax.swing.JTabbedPane();
        paDadosCompra = new javax.swing.JPanel();
        lblFornecedor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpCompra = new javax.swing.JTable();
        ftfFornecedor = new javax.swing.JFormattedTextField();
        bBuscarFornecedor = new javax.swing.JButton();
        lblDataCompra = new javax.swing.JLabel();
        ftfDataCompra = new javax.swing.JFormattedTextField();
        lblValorTotal = new javax.swing.JLabel();
        ftfValorTotal = new javax.swing.JFormattedTextField();
        paItensCompra = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        bAdicionarItem = new javax.swing.JButton();
        bRemoverItem = new javax.swing.JButton();
        ftfProduto = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpCompraItem = new javax.swing.JTable();
        bBuscarProduto = new javax.swing.JButton();
        lblQuantidade = new javax.swing.JLabel();
        spQuantidade = new javax.swing.JSpinner();
        lblValorUnitario = new javax.swing.JLabel();
        ftfValorUnitario = new javax.swing.JFormattedTextField();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        setClosable(true);
        setResizable(true);
        setTitle("Lançamento de Compra");

        bNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        bNovo.setMnemonic(KeyEvent.VK_N);
        bNovo.setText("Novo");
        bNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });

        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        bSalvar.setMnemonic(KeyEvent.VK_S);
        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finalizar.png"))); // NOI18N
        bFinalizar.setMnemonic(KeyEvent.VK_R);
        bFinalizar.setText("Finalizar");
        bFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFinalizarActionPerformed(evt);
            }
        });

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        bCancelar.setMnemonic(KeyEvent.VK_C);
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        bRemover.setMnemonic(KeyEvent.VK_R);
        bRemover.setText("Remover");
        bRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBarraFerramentasLayout = new javax.swing.GroupLayout(pBarraFerramentas);
        pBarraFerramentas.setLayout(pBarraFerramentasLayout);
        pBarraFerramentasLayout.setHorizontalGroup(
            pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFinalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancelar)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pBarraFerramentasLayout.setVerticalGroup(
            pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pBarraFerramentasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pBarraFerramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(bRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                    .addComponent(bNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFornecedor.setText("Fornecedor:");

        tpCompra.setModel(otmCompra);
        tpCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpCompra);

        bBuscarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        bBuscarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarFornecedorActionPerformed(evt);
            }
        });

        lblDataCompra.setText("Data da Compra:");

        ftfDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblValorTotal.setText("Valor Total:");

        ftfValorTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout paDadosCompraLayout = new javax.swing.GroupLayout(paDadosCompra);
        paDadosCompra.setLayout(paDadosCompraLayout);
        paDadosCompraLayout.setHorizontalGroup(
            paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
            .addGroup(paDadosCompraLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValorTotal)
                    .addComponent(lblDataCompra)
                    .addComponent(lblFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paDadosCompraLayout.createSequentialGroup()
                        .addComponent(ftfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBuscarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ftfValorTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(ftfDataCompra, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paDadosCompraLayout.setVerticalGroup(
            paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paDadosCompraLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBuscarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFornecedor)
                        .addComponent(ftfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCompra)
                    .addComponent(ftfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paDadosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(ftfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tpConteudoCompra.addTab("Dados da Compra", paDadosCompra);

        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProduto.setText("Produto:");

        bAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        bAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarItemActionPerformed(evt);
            }
        });

        bRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        bRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverItemActionPerformed(evt);
            }
        });

        tpCompraItem.setModel(otmCompraItem);
        jScrollPane2.setViewportView(tpCompraItem);

        bBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        bBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarProdutoActionPerformed(evt);
            }
        });

        lblQuantidade.setText("Quantidade:");

        lblValorUnitario.setText("Valor Unitário:");

        ftfValorUnitario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        javax.swing.GroupLayout paItensCompraLayout = new javax.swing.GroupLayout(paItensCompra);
        paItensCompra.setLayout(paItensCompraLayout);
        paItensCompraLayout.setHorizontalGroup(
            paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paItensCompraLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paItensCompraLayout.createSequentialGroup()
                        .addComponent(bAdicionarItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paItensCompraLayout.createSequentialGroup()
                        .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblValorUnitario)
                            .addComponent(lblQuantidade)
                            .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paItensCompraLayout.createSequentialGroup()
                                .addComponent(ftfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paItensCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        paItensCompraLayout.setVerticalGroup(
            paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paItensCompraLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProduto)
                        .addComponent(ftfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(spQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorUnitario)
                    .addComponent(ftfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paItensCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bRemoverItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAdicionarItem))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        tpConteudoCompra.addTab("Itens da Compra", paItensCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBarraFerramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tpConteudoCompra)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pBarraFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(tpConteudoCompra)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        compra = compraControl.novaCompra();
        habilitarFormulario(true);
        bFinalizar.setEnabled(false);
    }//GEN-LAST:event_bNovoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        habilitarFormulario(false);
        
        otmCompraItem.clear();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tpCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpCompraMouseClicked
        if (evt.getClickCount() >= 2) {
            compra = otmCompra.getValue(tpCompra.getSelectedRow());
            
            if (compra.getSituacao() == SituacaoEnum.FINALIZADA) {
                JOptionPane.showMessageDialog(this, "Compra finalizada não pode ser alterada.", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (compra.getSituacao() == SituacaoEnum.CANCELADA) {
                JOptionPane.showMessageDialog(this, "Compra cancelada não pode ser alterada.", "Alerta", JOptionPane.WARNING_MESSAGE);
                return;
            }

            ftfFornecedor.setValue(compra.getFornecedor());
            ftfDataCompra.setValue(compra.getDataCompra());
            ftfValorTotal.setValue(compra.getValorTotal());
            
            otmCompraItem.setData(compra.getItens());

            habilitarFormulario(true);

        }
    }//GEN-LAST:event_tpCompraMouseClicked

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        if (validarFormulario()) {
            
            salvarCompra(false);
            
            otmCompraItem.clear();
        }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void bFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFinalizarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente finalizar a compra?");
        if (opcao == 0) {
            salvarCompra(true);
        }
    }//GEN-LAST:event_bFinalizarActionPerformed

    private void bAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarItemActionPerformed
        
        if (validarFormularioItens()) {
            
            setarCompraItens();

            otmCompraItem.setData(compra.getItens());
            
            Double valorTotal = compra.getItens().stream().mapToDouble(v -> v.getValorUnitario() * v.getQuantidade()).sum();

            ftfValorTotal.setValue(valorTotal);

            limpaFormularioItens();
            
        }
        
        
    }//GEN-LAST:event_bAdicionarItemActionPerformed

    private void bRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverItemActionPerformed
        if (tpCompraItem.getSelectedRowCount() > 0) {
            
            int linhaSelecionada = tpCompraItem.getSelectedRow();
            CompraItem itemRemover = otmCompraItem.getValue(linhaSelecionada);

            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o endereço " + itemRemover + "?", "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
                compra.getItens().remove(itemRemover);
                otmCompraItem.setData(compra.getItens());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para remover.", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bRemoverItemActionPerformed

    private void bRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRemoverActionPerformed

    private void bBuscarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarFornecedorActionPerformed
        TelaBuscaFornecedor buscaFornecedor = new TelaBuscaFornecedor(this);
        buscaFornecedor.setVisible(true);
    }//GEN-LAST:event_bBuscarFornecedorActionPerformed

    private void bBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarProdutoActionPerformed
        TelaBuscaProduto buscaProduto = new TelaBuscaProduto(this);
        buscaProduto.setVisible(true);
    }//GEN-LAST:event_bBuscarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionarItem;
    private javax.swing.JButton bBuscarFornecedor;
    private javax.swing.JButton bBuscarProduto;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bFinalizar;
    private javax.swing.JButton bNovo;
    private javax.swing.JButton bRemover;
    private javax.swing.JButton bRemoverItem;
    private javax.swing.JButton bSalvar;
    private javax.swing.ButtonGroup bgClienteTipo;
    private javax.swing.JFormattedTextField ftfDataCompra;
    private javax.swing.JFormattedTextField ftfFornecedor;
    private javax.swing.JFormattedTextField ftfProduto;
    private javax.swing.JFormattedTextField ftfValorTotal;
    private javax.swing.JFormattedTextField ftfValorUnitario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDataCompra;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorUnitario;
    private javax.swing.JPanel pBarraFerramentas;
    private javax.swing.JPanel paDadosCompra;
    private javax.swing.JPanel paItensCompra;
    private javax.swing.JSpinner spQuantidade;
    private javax.swing.JTable tpCompra;
    private javax.swing.JTable tpCompraItem;
    private javax.swing.JTabbedPane tpConteudoCompra;
    // End of variables declaration//GEN-END:variables

private void habilitarFormulario(boolean b) {
    
        bNovo.setEnabled(!b);
        bSalvar.setEnabled(b);
        bFinalizar.setEnabled(b);
        bRemover.setEnabled(b);
        bCancelar.setEnabled(b);
        ftfFornecedor.setEnabled(b);
        bBuscarFornecedor.setEnabled(b);
        ftfDataCompra.setEnabled(b);
        ftfValorTotal.setEnabled(b);
        ftfProduto.setEnabled(b);
        bBuscarProduto.setEnabled(b);
        spQuantidade.setEnabled(b);
        ftfValorUnitario.setEnabled(b);
        bAdicionarItem.setEnabled(b);
        bRemoverItem.setEnabled(b);
        tpCompra.setEnabled(!b);
        
        if (!b) {
            limpaFormulario();
        }

    }
    
    private void setarCompraItens() {
        
        CompraItem compraItem = new CompraItem();
        compraItem.setProduto((Produto) ftfProduto.getValue());
        compraItem.setCompra(compra);
        compraItem.setQuantidade(Long.parseLong(String.valueOf(spQuantidade.getValue())));
        compraItem.setValorUnitario(Double.parseDouble(String.valueOf(ftfValorUnitario.getValue())));

        compra.getItens().add(compraItem);
    } 
    
    private void salvarCompra(boolean finalizar) {
        
        if (validarFormulario()) {
            compra.setFornecedor((Fornecedor) ftfFornecedor.getValue());
            compra.setDataCompra((Date) ftfDataCompra.getValue());
            compra.setValorTotal((Double) ftfValorTotal.getValue());
            if (finalizar) {
                compra.setSituacao(SituacaoEnum.FINALIZADA);
            } else {
                compra.setSituacao(SituacaoEnum.ABERTA);
            }

            if (compra.getCodigo() == 0) {
                try {
                    compraControl.inserirCompra(compra);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir a compra.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                try {
                    compraControl.alterarCompra(compra);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao alterar a compra.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            habilitarFormulario(false);
            carregarGrade();
        }
    }
    
    private boolean validarFormulario() {
        if (ftfFornecedor.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Fornecedor inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfFornecedor.requestFocus();
            return false;
        }
        if (compra.getItens().size() == 0) {
            JOptionPane.showMessageDialog(this, "Quantidade de itens inválida.", "Alerta", JOptionPane.WARNING_MESSAGE);
            tpConteudoCompra.setSelectedIndex(1);
            return false;
        }
        return true;
    }

    private boolean validarFormularioItens() {
        if (ftfProduto.getValue() == null) {
            JOptionPane.showMessageDialog(this, "Produto inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            ftfProduto.requestFocus();
            return false;
        }
        return true;
    }
    
    private void limpaFormulario() {
        compra = null;
        ftfFornecedor.setValue(null);
        ftfDataCompra.setValue(new Date());
        ftfValorTotal.setValue(new Double(0));
        ftfProduto.setValue(null);
        spQuantidade.setValue(1);
        ftfValorUnitario.setValue(new Double(0));
        tpCompraItem.setModel(otmCompraItem);
        limpaFormularioItens();
    }
    
    private void limpaFormularioItens() {
        ftfProduto.setValue(null);
        spQuantidade.setValue(1);
        ftfValorUnitario.setValue(new Double(0));
    }

}
