/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lucas.sysvendas.view.consultas;

import com.lucas.sysvendas.control.ProdutoControl;
import com.lucas.sysvendas.model.domain.Produto;
import com.lucas.sysvendas.util.exceptions.ErroException;
import com.lucas.sysvendas.view.cadastro.TelaCompra;
import com.lucas.sysvendas.view.venda.TelaVenda;
import com.towel.swing.table.ObjectTableModel;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lucas
 */
public class TelaBuscaProduto extends javax.swing.JDialog {
    
    JInternalFrame parent;
    
    private final ObjectTableModel<Produto> otmFiltroProduto = new ObjectTableModel<>(Produto.class, "descricao");
    
    private final ProdutoControl produtoControl = new ProdutoControl();

    /**
     * Creates new form TelaModalDepartamento
     * @param parent
     */
    public TelaBuscaProduto(JInternalFrame parent) {
        super();
        this.parent = parent;
        initComponents();
        carregarGrade();
    }
    
    private void carregarGrade() {
        
        try {      
            otmFiltroProduto.setData(produtoControl.listarTodos());
        } catch (ErroException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar grade.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFiltro = new javax.swing.JPanel();
        lblFiltroProduto = new javax.swing.JLabel();
        txtFiltroProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpFiltroProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Departamento");
        setModal(true);

        lblFiltroProduto.setText("Filtro:");

        txtFiltroProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroProdutoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pFiltroLayout = new javax.swing.GroupLayout(pFiltro);
        pFiltro.setLayout(pFiltroLayout);
        pFiltroLayout.setHorizontalGroup(
            pFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltroProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pFiltroLayout.setVerticalGroup(
            pFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltroProduto)
                    .addComponent(txtFiltroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tpFiltroProduto.setModel(otmFiltroProduto);
        tpFiltroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpFiltroProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpFiltroProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroProdutoKeyReleased
        TableRowSorter rs = new TableRowSorter(otmFiltroProduto);
        rs.setRowFilter(RowFilter.regexFilter("(?i)" + txtFiltroProduto.getText().trim()));
        tpFiltroProduto.setRowSorter(rs);
    }//GEN-LAST:event_txtFiltroProdutoKeyReleased

    private void tpFiltroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpFiltroProdutoMouseClicked
        if (evt.getClickCount() >= 2) {
            
            Produto produto = null;
            
            if (tpFiltroProduto.getRowSorter() != null) {
                int linhaSelecionada = tpFiltroProduto.getRowSorter().convertRowIndexToModel(tpFiltroProduto.getSelectedRow());
                produto = otmFiltroProduto.getValue(linhaSelecionada);
            } else {
                produto = otmFiltroProduto.getValue(tpFiltroProduto.getSelectedRow());
            }

            if (parent instanceof TelaCompra) {
                TelaCompra tc = (TelaCompra) parent;
                tc.setProduto(produto);
                dispose();
            } else if (parent instanceof TelaVenda) {
                TelaVenda tc = (TelaVenda) parent;
                tc.setProduto(produto);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Campo de destino inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_tpFiltroProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaBuscaProduto dialog = new TelaBuscaProduto(new javax.swing.JInternalFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltroProduto;
    private javax.swing.JPanel pFiltro;
    private javax.swing.JTable tpFiltroProduto;
    private javax.swing.JTextField txtFiltroProduto;
    // End of variables declaration//GEN-END:variables
}
